CAM-925
FlawlessTheory/skypelab-bot-alt pull request #1
Opened 2020-07-23 09:44 UTC by FlawlessTheory

CAM-925

2020-07-23 09:55 UTC, nikitamugen requested changes
Не совсем понял где идет работа с самой СУБД, если честно.

2020-07-23 09:55 UTC, nikitamugen commented on bot.js
> +	} else {
А мы таким образом на один канал не можем сделать несколько подписок ?

2020-07-23 09:55 UTC, nikitamugen commented on bot.js
> +	});
Можно заюзать метод filter. И в качестве резельтата отдавать кол-во записей в отфильтрованном массиве. Если больше 0, то запись найдена. Так проще и нагляднее, я считаю :)

2020-07-23 10:04 UTC, FlawlessTheory commented on bot.js
> +	} else {
На один канал можно сделать несколько подписок. Эта проверка не позволяет по несколько раз записать один и тот же идентификатор канала в БД

2020-07-24 03:01 UTC, nikitamugen approved these changes

2020-07-24 03:01 UTC, merged